appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: V+MhVkhZVTYDsc77Bh+hEGQ77sx/ucgUhI3S9RKtjEI69npVdec9HfRiMB6xqvElv06Yl/yU2MZjSJWFyXKmAJD3UQWP89RtNj0kaqHPXITr0guqmaEmSCHYwN4jf/C52l8bh5SJY4R86zce++MuIEGGxsHqsm5w6Z9VLiN7WC0RQMCJahdm0P28Lgy2CnJW1BjpPTwJqLmePNwNIv1nTFgtdt3yMN6bnA7vC2PWGBmKt8+c0o5exr8iA4plq67e4c3nJM3PF68M0PPqzLLo9R9kH1+1DSmDmwF6FHwnOoKnc7BUmV/eXdF/6+oPC78ReSxWY+SgmOqS6VV6V67qoO2Lk5CmZKBA1x/IvLpwgVXW+GrZkhpza2rpAwEDHSDpIlzHV2OzeYi0InPyTDXlwoPyQ78XAWZ4zjqWa1rzvJ7vHf7fuDICvvhhKhKdvakqP6CDuHAleNOWMWUYG80Ahw30vvjXwzGZFp4aY+WDJuGV7z/pqOLGimk8jTrAgQda9sR/0I5+rowOiX1nAuOlX4XlgALlgQqBMAbxyWuXuxogZtqqxnOHqdy+f2ik2W2lKmpYOFthz7dMeDRP5MJJzlRKP+4kjs0SBvM60nh/FbiJPvu3DASsS2BbAQ6MQXjOFVISIInQMu4MqVVwIb6iGI4+5d8gn7FjpC0rKH1R3i8=}
